name: Close PR delete firebase channel
on:
  pull_request:
    types: [closed]
jobs:
  delete_firebase_channel:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - id: get-short-name
        run: |
          id=$(echo ${{github.event.pull_request.head.ref}} | cut -c 1-20)
          echo "id=$id" >> $GITHUB_OUTPUT
      - name: Delete Preview Channel on Firebase
        uses: w9jds/firebase-action@v13.2.1
        with:
          args: hosting:channel:delete pr${{github.event.number}}-${{steps.get-short-name.outputs.id}} --force
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: cioos-metadata-form-dev-258dc
          GITHUB_AUTH: ${{ secrets.ISSUE_CREATOR_PAT }}